title: Advertype
description: "A website for typography "
footer_text: Copyright 2021 Taylor Ball
header_feature_image: ../uploads/4.png
header_text: ""
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/logonew.png
favicon: ../uploads/untitled-3.png
gridlayout: true
fixednavbar: true
upzoom: true
items: []
