title: Advertype
description: "A website for typography "
footer_text: Copyright 2021 Taylor Ball
header_feature_image: ../uploads/florian-wehde-ivw7mzpwd4g-unsplash.jpg
header_text: "Advertype "
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/lowo-new-2.png
favicon: ../uploads/lowo-new-2.png
gridlayout: false
fixednavbar: false
upzoom: true
items: []
