title: Advertype
description: "A website for typography "
footer_text: Copyright 2021 Taylor Ball
header_feature_image: ../uploads/banner-draft.-png.png
header_text: "Advertype "
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/untitled-3.png
favicon: ../uploads/untitled-3.png
gridlayout: true
fixednavbar: false
upzoom: true
items: []
